// Display names from the Japanese edition's stage and music localization tables.
// English song titles are intentionally preserved exactly as named in that edition.
export const STAGE_NAMES_JA = Object.freeze({
  "1": "市街地中枢・交差点",
  "2": "高層建築・屋上",
  "3": "静寂の公園",
  "4": "川沿いの広場",
  "5": "高速道路・下層部",
  "6": "琥珀色の高架下",
  "7": "明灯の商業施設",
  "8": "守人の社",
  "9": "煌朧の祭壇",
  "10": "紅く染まる駐車場",
  "11": "朽ち荒れた廃墟",
  "12": "鳴動の工業施設",
  "13": "眠りの噴水広場",
  "14": "桜咲き散る旧校舎",
  "15": "電影のカフェテリア",
  "16": "もみじ横町前通り",
  "17": "環堺東・児童遊園",
  "18": "極東の大聖堂",
  "19": "光と水のアートミュージアム",
  "20": "月影に佇む天文台",
  "21": "夜の校舎・正面玄関前",
  "22": "深淵・永劫の祭壇",
  "23": "煌朧のナイトプール",
  "24": "忘却の森・荒涼霊域",
  "25": "市街地北・中央通り",
  "26": "深碧のアクアリウム",
  "27": "夜闇に聳える塔・建設中",
  "90": "トレーニングステージ"
});

export const MUSIC_NAMES_JA = Object.freeze({
  "1": "Scraper Sky High",
  "2": "Night Walker",
  "3": "Maximize Power!",
  "4": "Bad Surface",
  "5": "Purity & Strictly",
  "6": "Rushing Heart",
  "7": "Unseen Entities",
  "8": "Snow Sisters",
  "9": "Monochrome Memory",
  "10": "歩く姿は百合の花♪",
  "11": "Relatively Despair",
  "12": "Blood Drain -Again-",
  "13": "Gallant Girl \"Sora yori Nagare, Hasiru Kaze\"",
  "14": "Beat Eat Nest",
  "15": "開戰 -Again-",
  "16": "Erudite Eyes",
  "17": "Flame & Destiny",
  "18": "Extreme Stream",
  "19": "Icefield White Knight",
  "20": "Keep on Shining!",
  "21": "Pandemonium Party",
  "22": "Forceful Step",
  "23": "Tearing Bullet",
  "24": "Rebirth, Immortal Advent",
  "25": "Sound of Night Wind",
  "26": "Fierce battle? No way",
  "27": "Elefee's Healing Magic",
  "40": "Long-await Final Screening",
  "41": "Load Exist",
  "50": "Omen of Darkness",
  "52": "Unbreakable Will",
  "53": "Determination",
  "54": "Broken Chain",
  "55": "Dark Awake",
  "56": "What a Coincidence",
  "57": "Creeping Shadow",
  "58": "Inevitable Conflict",
  "62": "輪廻の終焉へ",
  "70": "もう怯えないで",
  "71": "Close Your Eyes",
  "82": "Still Stand?",
  "83": "See You Somewhere...",
  "84": "Demons & Snakes",
  "91": "Cross Thought",
  "92": "Mutual Situation",
  "93": "Incompatible Relation",
  "98": "No Medication",
  "99": "Begin System Celestial..."
});

export const stageNameJa = (id) => Number.isInteger(id) ? STAGE_NAMES_JA[id] || null : null;
export const musicNameJa = (id) => Number.isInteger(id) ? MUSIC_NAMES_JA[id] || null : null;
